version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3.8.3
    ports:
      - "2181:2181"
    container_name: zk_test_node
    environment:
      ALLOW_ANONYMOUS_LOGIN: "true"
  kafka:
    image: bitnami/kafka:3.6.0
    ports:
      - "9092:9092"
    container_name: kafka_test_node
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
